---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: debian9
    image: debian:9
    privileged: true
  - name: debian10
    image: debian:10
    privileged: true
  - name: rhel8
    image: registry.redhat.io/ubi8
    privileged: true
  - name: rhel7
    image: registry.redhat.io/ubi7
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
